-- Seed EchelonAccess with the same relationship intelligence data used by lib/mock-data.ts.
--
-- Before running:
-- 1. Sign in to the app once so Supabase creates your auth user.
-- 2. In Supabase Dashboard > Authentication > Users, copy your user id.
-- 3. Replace the placeholder below with that user id.

do $$
declare
  owner_user_id uuid := '00000000-0000-0000-0000-000000000000';
  seeded_workspace_id uuid := gen_random_uuid();
begin
  if owner_user_id = '00000000-0000-0000-0000-000000000000' then
    raise exception 'Replace owner_user_id in supabase/seed.sql with a real Supabase auth.users.id before running.';
  end if;

  insert into workspaces (id, name, slug, owner_id)
  values (seeded_workspace_id, 'Private Relationship Desk', 'private-relationship-desk', owner_user_id)
  on conflict (slug) do update
    set name = excluded.name,
        owner_id = excluded.owner_id,
        updated_at = now()
  returning id into seeded_workspace_id;

  insert into workspace_members (workspace_id, user_id, role)
  values (seeded_workspace_id, owner_user_id, 'owner')
  on conflict (workspace_id, user_id) do update
    set role = excluded.role;

  insert into organizations (
    id, workspace_id, name, normalized_name, type, sector, country, city, tags
  ) values
  (
    '10000000-0000-4000-8000-000000000001',
    seeded_workspace_id,
    'Northbridge Capital',
    'northbridge capital',
    'fund',
    'Infrastructure',
    'United Kingdom',
    'London',
    array['fund','infrastructure','energy']
  ),
  (
    '10000000-0000-4000-8000-000000000002',
    seeded_workspace_id,
    'Ministry of Trade, Brazil',
    'ministry of trade brazil',
    'government',
    'Trade',
    'Brazil',
    'Brasilia',
    array['government','latin-america']
  ),
  (
    '10000000-0000-4000-8000-000000000003',
    seeded_workspace_id,
    'Harborline Growth',
    'harborline growth',
    'fund',
    'Growth Equity',
    'Singapore',
    'Singapore',
    array['apac','logistics','fund']
  )
  on conflict (id) do update set
    workspace_id = excluded.workspace_id,
    name = excluded.name,
    normalized_name = excluded.normalized_name,
    type = excluded.type,
    sector = excluded.sector,
    country = excluded.country,
    city = excluded.city,
    tags = excluded.tags,
    deleted_at = null,
    updated_at = now();

  insert into people (
    id, workspace_id, canonical_name, display_name, aliases, relationship_strength, trust_level, warmth_status,
    current_title, current_organization, last_interaction, geography, sector_tags, source_count,
    mandate_matches, review_status, notes, opposition, nationality, languages, public_private_status,
    influence_type, access_path, relationship_owner, best_approach, current_authority, historical_authority,
    sensitivity_level, motivations, constraints, relevant_mandates, relevant_geographies, relevant_sectors,
    relevant_institutions, key_relationships, do_not_discuss, best_next_move, source_confidence, last_verified_date
  ) values
  (
    '00000000-0000-4000-8000-000000000001',
    seeded_workspace_id,
    'Amelia Hart',
    'Amelia Hart',
    array['A. Hart'],
    5,
    'high',
    'direct',
    'Partner, Strategic Infrastructure',
    'Northbridge Capital',
    '2026-05-18',
    'London / New York',
    array['Infrastructure','Energy','Sovereign'],
    9,
    3,
    'verified',
    'Can be approached directly when the ask is precise and well-framed.',
    'May face resistance from incumbent port operators and local ministries wary of foreign capital control.',
    'United Kingdom',
    array['English','French'],
    'Public-private bridge',
    'Introducer / capital allocator',
    'Direct relationship; best through a precise one-page mandate brief.',
    'Private operator desk',
    'Formal email followed by a short working call.',
    'Can validate fund appetite and introduce infrastructure counterparties.',
    'Former UK trade role gives context on sovereign and ministry channels.',
    'moderate',
    'High-quality infrastructure mandates, credible counterparties, reputationally clean capital.',
    'Avoid appearing to lobby former government colleagues informally.',
    array['Port Modernization Capital Path'],
    array['United Kingdom','West Africa'],
    array['Infrastructure','Energy'],
    array['Northbridge Capital','UK Department for Business and Trade'],
    'Former trade officials, infrastructure fund partners, UK-Africa commercial channels.',
    'Do not frame the ask as political access or privileged government influence.',
    'Send targeted infrastructure brief after mandate terms are tightened.',
    0.92,
    '2026-05-18'
  ),
  (
    '00000000-0000-4000-8000-000000000002',
    seeded_workspace_id,
    'Rafael Santos',
    'Rafael Santos',
    array['Rafa Santos'],
    4,
    'moderate',
    'warm',
    'Senior Advisor',
    'Ministry of Trade, Brazil',
    '2026-03-07',
    'Brasilia',
    array['Government','Trade','Latin America'],
    6,
    2,
    'needs_review',
    'Historical card indicates prior private-sector role that may matter for energy mandate.',
    'Likely constrained by domestic political scrutiny around energy privatization and trade concessions.',
    'Brazil',
    array['Portuguese','English','Spanish'],
    'Government',
    'Policy advisor / gatekeeper',
    'Warm path; requires policy-safe framing and ministry protocol.',
    'Latin America coverage',
    'Intro request through trusted trade contact with noncommercial policy context.',
    'Can interpret ministry priorities and direct appropriate energy-policy access points.',
    'Prior private-sector advisory work may explain sponsor relationships.',
    'high',
    'Trade development, national energy security, avoiding public-sector controversy.',
    'Procurement optics and domestic political sensitivity around privatization.',
    array['Latin America Energy Introductions'],
    array['Brazil','Chile'],
    array['Government','Energy','Trade'],
    array['Ministry of Trade, Brazil'],
    'Ministry staff, trade attachés, energy transition sponsors.',
    'Avoid commercial compensation, preferential access, or concession language.',
    'Resolve current title and confirm whether private-sector role remains relevant.',
    0.78,
    '2026-03-07'
  ),
  (
    '00000000-0000-4000-8000-000000000003',
    seeded_workspace_id,
    'Maya Chen',
    'Maya Chen',
    array[]::text[],
    3,
    'moderate',
    'known',
    'Managing Director',
    'Harborline Growth',
    '2025-11-12',
    'Singapore',
    array['Growth Equity','Logistics','APAC'],
    4,
    1,
    'verified',
    'Best reached through an event-specific pretext or a mutual Asia logistics contact.',
    'Competitive tension with regional logistics consolidators and sovereign-linked investors.',
    'Singapore',
    array['English','Mandarin'],
    'Private sector',
    'Investor / sector validator',
    'Event-specific pretext or mutual APAC logistics contact.',
    'APAC growth desk',
    'Conference follow-up with a focused logistics growth thesis.',
    'Can validate growth equity appetite and identify regional operating sponsors.',
    'Known logistics network across Singapore and Indonesia.',
    'moderate',
    'Scalable logistics platforms, credible operators, regional growth visibility.',
    'Avoid conflicts with existing portfolio or sovereign-linked co-investors.',
    array['Strategic Growth Equity Access'],
    array['Singapore','Indonesia'],
    array['Growth Equity','Logistics'],
    array['Harborline Growth'],
    'APAC logistics operators, growth funds, conference network.',
    'Avoid naming competitors without permission.',
    'Use a logistics event as the opening context.',
    0.84,
    '2025-11-12'
  ),
  (
    '00000000-0000-4000-8000-000000000004',
    seeded_workspace_id,
    'James Okafor',
    'James Okafor',
    array['J. Okafor'],
    2,
    'unknown',
    'weak',
    'Board Member',
    'Atlantic Development Bank',
    '2024-09-22',
    'Accra / Lagos',
    array['Development Finance','Ports','Africa'],
    3,
    2,
    'possible_duplicate',
    'Two cards may be the same person with title progression.',
    'Possible board-level caution around reputational exposure and development-bank procurement rules.',
    'Ghana / Nigeria',
    array['English'],
    'Development finance',
    'Board validator / institutional gatekeeper',
    'Indirect path; duplicate identity should be resolved before outreach.',
    'Africa infrastructure coverage',
    'Confirm identity, then approach through an institutional context.',
    'May validate development-finance fit and identify governance concerns.',
    'Prior board and card history may show title progression.',
    'high',
    'Governance quality, development impact, procurement integrity.',
    'Development-bank procurement rules and reputational exposure.',
    array['Port Modernization Capital Path'],
    array['West Africa','Ghana','Nigeria'],
    array['Development Finance','Ports'],
    array['Atlantic Development Bank'],
    'Development bank board members, port finance contacts.',
    'Do not imply bypassing procurement or board process.',
    'Resolve duplicate records before any mandate-specific outreach.',
    0.64,
    '2024-09-22'
  )
  on conflict (id) do update set
    workspace_id = excluded.workspace_id,
    canonical_name = excluded.canonical_name,
    display_name = excluded.display_name,
    aliases = excluded.aliases,
    relationship_strength = excluded.relationship_strength,
    trust_level = excluded.trust_level,
    warmth_status = excluded.warmth_status,
    current_title = excluded.current_title,
    current_organization = excluded.current_organization,
    last_interaction = excluded.last_interaction,
    geography = excluded.geography,
    sector_tags = excluded.sector_tags,
    source_count = excluded.source_count,
    mandate_matches = excluded.mandate_matches,
    review_status = excluded.review_status,
    notes = excluded.notes,
    opposition = excluded.opposition,
    nationality = excluded.nationality,
    languages = excluded.languages,
    public_private_status = excluded.public_private_status,
    influence_type = excluded.influence_type,
    access_path = excluded.access_path,
    relationship_owner = excluded.relationship_owner,
    best_approach = excluded.best_approach,
    current_authority = excluded.current_authority,
    historical_authority = excluded.historical_authority,
    sensitivity_level = excluded.sensitivity_level,
    motivations = excluded.motivations,
    constraints = excluded.constraints,
    relevant_mandates = excluded.relevant_mandates,
    relevant_geographies = excluded.relevant_geographies,
    relevant_sectors = excluded.relevant_sectors,
    relevant_institutions = excluded.relevant_institutions,
    key_relationships = excluded.key_relationships,
    do_not_discuss = excluded.do_not_discuss,
    best_next_move = excluded.best_next_move,
    source_confidence = excluded.source_confidence,
    last_verified_date = excluded.last_verified_date,
    deleted_at = null,
    updated_at = now();

  insert into roles (
    id, workspace_id, person_id, organization_id, organization_name, title, start_date, end_date, is_current, confidence, source_label
  ) values
  (
    '20000000-0000-4000-8000-000000000001',
    seeded_workspace_id,
    '00000000-0000-4000-8000-000000000001',
    '10000000-0000-4000-8000-000000000001',
    'Northbridge Capital',
    'Partner, Strategic Infrastructure',
    '2023',
    null,
    true,
    0.92,
    'Manual update'
  ),
  (
    '20000000-0000-4000-8000-000000000002',
    seeded_workspace_id,
    '00000000-0000-4000-8000-000000000001',
    null,
    'UK Department for Business and Trade',
    'Deputy Trade Commissioner',
    '2012',
    '2018',
    false,
    0.86,
    'Business card OCR'
  ),
  (
    '20000000-0000-4000-8000-000000000003',
    seeded_workspace_id,
    '00000000-0000-4000-8000-000000000001',
    null,
    'Helios Energy Group',
    'Head of Public-Private Partnerships',
    '2018',
    '2023',
    false,
    0.78,
    'Public profile'
  )
  on conflict (id) do update set
    workspace_id = excluded.workspace_id,
    person_id = excluded.person_id,
    organization_id = excluded.organization_id,
    organization_name = excluded.organization_name,
    title = excluded.title,
    start_date = excluded.start_date,
    end_date = excluded.end_date,
    is_current = excluded.is_current,
    confidence = excluded.confidence,
    source_label = excluded.source_label,
    deleted_at = null,
    updated_at = now();

  insert into interactions (
    id, workspace_id, person_id, interaction_date, type, summary, outcome, next_step, confidence, source_label
  ) values
  (
    '30000000-0000-4000-8000-000000000001',
    seeded_workspace_id,
    '00000000-0000-4000-8000-000000000001',
    '2026-05-18',
    'call',
    'Discussed sovereign-backed port modernization mandate and likely counterparties.',
    'Open to a specific one-page ask.',
    'Send targeted brief after mandate terms are tightened.',
    0.95,
    'User note'
  ),
  (
    '30000000-0000-4000-8000-000000000002',
    seeded_workspace_id,
    '00000000-0000-4000-8000-000000000001',
    '2025-10-04',
    'event',
    'Reconnected at infrastructure forum; mentioned move from energy advisory into fund role.',
    null,
    null,
    0.84,
    'Event note'
  ),
  (
    '30000000-0000-4000-8000-000000000003',
    seeded_workspace_id,
    '00000000-0000-4000-8000-000000000001',
    '2012-01-01',
    'note',
    'Original card captured Deputy Trade Commissioner title and London office number.',
    null,
    null,
    0.76,
    'Business card OCR'
  )
  on conflict (id) do update set
    workspace_id = excluded.workspace_id,
    person_id = excluded.person_id,
    interaction_date = excluded.interaction_date,
    type = excluded.type,
    summary = excluded.summary,
    outcome = excluded.outcome,
    next_step = excluded.next_step,
    confidence = excluded.confidence,
    source_label = excluded.source_label,
    deleted_at = null,
    updated_at = now();

  insert into mandates (
    id, workspace_id, client_name, title, objective, sector, geography, status, relevant_contacts, next_action
  ) values
  (
    '40000000-0000-4000-8000-000000000001',
    seeded_workspace_id,
    'Confidential infrastructure client',
    'Port Modernization Capital Path',
    'Identify warm government and fund counterparties for port modernization financing.',
    'Infrastructure',
    array['West Africa','United Kingdom'],
    'active',
    11,
    'Approve outreach angle for Amelia Hart'
  ),
  (
    '40000000-0000-4000-8000-000000000002',
    seeded_workspace_id,
    'Energy transition sponsor',
    'Latin America Energy Introductions',
    'Map trade and energy-policy access points for regional expansion.',
    'Energy',
    array['Brazil','Chile'],
    'researching',
    7,
    'Resolve Rafael Santos role history'
  ),
  (
    '40000000-0000-4000-8000-000000000003',
    seeded_workspace_id,
    'APAC logistics operator',
    'Strategic Growth Equity Access',
    'Find investor and sovereign logistics paths across Singapore and Indonesia.',
    'Logistics',
    array['Singapore','Indonesia'],
    'draft',
    5,
    'Define forbidden contacts before matching'
  )
  on conflict (id) do update set
    workspace_id = excluded.workspace_id,
    client_name = excluded.client_name,
    title = excluded.title,
    objective = excluded.objective,
    sector = excluded.sector,
    geography = excluded.geography,
    status = excluded.status,
    relevant_contacts = excluded.relevant_contacts,
    next_action = excluded.next_action,
    deleted_at = null,
    updated_at = now();

  update mandates set
    mandate_category = 'Infrastructure finance',
    deal_type = 'PPP / concession financing',
    ask_type = 'Capital path, government access, and strategic counterparty mapping',
    transaction_type = 'Public-private infrastructure modernization',
    client_profile = 'Private infrastructure operator seeking credible sovereign-adjacent financing paths.',
    sponsor_profile = 'Operator-led platform with port modernization mandate and public-sector interfaces.',
    jurisdiction = array['United Kingdom','Ghana','Nigeria'],
    target_counterparty_types = array['Infrastructure funds','DFIs','trade ministries','port authorities','sovereign advisors'],
    desired_counterparties = array['Northbridge Capital','UK Department for Business and Trade','Atlantic Development Bank'],
    forbidden_contacts = array['Direct procurement officials before counsel approval'],
    capital_type = 'Project finance / structured growth capital',
    capital_stack = 'Senior debt, DFI tranche, strategic equity, political risk insurance',
    target_amount = 'USD 150M-300M',
    minimum_ticket = 'USD 25M',
    currency = 'USD',
    economics = 'Long-dated infrastructure yield with concession-linked cash flow.',
    fee_model = 'Success fee plus advisory retainer',
    transaction_stage = 'Mandate shaping',
    timeline = 'Six to nine months to credible financing path',
    urgency = 'high',
    decision_deadline = '2026-08-15',
    close_target_date = '2027-03-31',
    regulatory_regime = 'Port concession, foreign investment, procurement, development-finance safeguards',
    compliance_requirements = 'Anti-bribery, sanctions screening, beneficial ownership, public procurement review',
    sanctions_exposure = 'Low direct exposure; screen contractors, port users, and state-linked counterparties.',
    political_exposure = 'High because port infrastructure touches sovereign logistics and labor interests.',
    procurement_process = 'Must avoid informal bypass of public tender or concession amendment process.',
    government_touchpoints = array['Trade ministry','Port authority','Investment promotion agency'],
    required_approvals = array['Client board','Local counsel','Procurement counsel','Government relations review'],
    decision_makers = array['Client CEO','Ministerial sponsor','Port authority board','DFI investment committee'],
    gatekeepers = array['Chief of staff','Legal counsel','Development bank country lead'],
    influencers = array['Former trade officials','Infrastructure fund partners','Port operating advisors'],
    buyer_universe = array['Strategic port operators','Infrastructure platforms'],
    investor_universe = array['Infrastructure funds','DFIs','Sovereign-linked capital','Pension capital'],
    strategic_partners = array['Engineering firms','Political risk insurers','Local operators'],
    relationship_thesis = 'Amelia Hart bridges fund authority and UK-Africa trade infrastructure context.',
    access_strategy = 'Start with validated fund appetite, then move to government-facing introductions only after compliance framing.',
    outreach_angle = 'Modernization finance with transparent governance and development impact.',
    value_proposition = 'Credible operator, bankable modernization plan, de-risked government interface.',
    proof_points = array['Existing operator mandate','Modernization capex plan','Trade corridor impact'],
    materials_required = array['One-page mandate','Capex summary','Governance memo','Counterparty shortlist'],
    diligence_requirements = array['Concession status','Environmental and social review','Beneficial ownership','Procurement history'],
    data_room_status = 'Early materials only',
    confidentiality_level = 'highly_confidential',
    conflict_constraints = 'Avoid current procurement officials and any conflicted former advisors.',
    competitive_landscape = 'Incumbent port operators and regional logistics groups may resist new capital path.',
    incumbent_relationships = 'Existing local operator relationships need mapping before outreach.',
    risks = 'Political optics, procurement sensitivity, concession ambiguity, labor opposition.',
    blockers = 'Unclear concession amendment path and uncertain ministry sponsor.',
    open_questions = array['Who is the legitimate public-sector sponsor?','What concession rights can be financed?','Which DFI safeguards apply?'],
    success_criteria = array['Three warm investor conversations','One government-safe access path','Compliance-approved outreach narrative'],
    disqualification_criteria = array['Requires improper public official contact','Counterparty fails sanctions or beneficial ownership review'],
    next_milestone = 'Approve one-page mandate and compliance-safe outreach angle',
    owner = 'Infrastructure desk',
    priority = 'critical',
    source_confidence = 0.86,
    last_reviewed_date = '2026-06-20',
    tags = array['PPP','ports','project-finance','sovereign-interface'],
    notes = 'Treat as relationship-led origination with strict compliance gating.'
  where id = '40000000-0000-4000-8000-000000000001';

  update mandates set
    mandate_category = 'Market entry and policy access',
    deal_type = 'Government access / strategic expansion',
    ask_type = 'Policy readout, regulator mapping, and energy-sector introductions',
    transaction_type = 'Cross-border market entry',
    client_profile = 'Energy transition sponsor evaluating Latin America expansion.',
    sponsor_profile = 'Commercial sponsor seeking policy-safe introductions before capital deployment.',
    jurisdiction = array['Brazil','Chile'],
    target_counterparty_types = array['Trade advisors','energy regulators','ministry policy staff','local sponsors','utilities'],
    desired_counterparties = array['Ministry of Trade, Brazil','energy transition sponsors','regional utilities'],
    forbidden_contacts = array['Officials involved in active procurement processes'],
    capital_type = 'Strategic expansion capital',
    capital_stack = 'Sponsor equity with potential local debt',
    target_amount = 'To be defined after market access readout',
    minimum_ticket = 'N/A',
    currency = 'USD / BRL / CLP',
    economics = 'Market-entry optionality before project-level commitment.',
    fee_model = 'Monthly advisory plus milestone fee',
    transaction_stage = 'Researching',
    timeline = 'Ninety-day access and policy map',
    urgency = 'medium',
    decision_deadline = '2026-09-01',
    close_target_date = '2026-12-15',
    regulatory_regime = 'Energy policy, foreign investment, trade promotion, utility regulation',
    compliance_requirements = 'Government contact protocol, anti-bribery review, lobbying analysis',
    sanctions_exposure = 'Low but screen local intermediaries and politically exposed persons.',
    political_exposure = 'Medium-high due to energy pricing, privatization sensitivity, and elections.',
    procurement_process = 'No procurement participation until counsel defines guardrails.',
    government_touchpoints = array['Trade ministry','Energy regulator','Investment promotion agencies'],
    required_approvals = array['Client strategy lead','Government-contact protocol','Local counsel'],
    decision_makers = array['Sponsor CEO','Regional expansion lead','Policy sponsor'],
    gatekeepers = array['Ministry advisor','Trade attaché','Local legal counsel'],
    influencers = array['Former energy officials','utility executives','trade associations'],
    buyer_universe = array['Utilities','industrial offtakers','regional developers'],
    investor_universe = array['Strategic energy investors','climate funds','local banks'],
    strategic_partners = array['Local developers','utility partners','policy advisors'],
    relationship_thesis = 'Rafael Santos may clarify policy context but needs role-history resolution before approach.',
    access_strategy = 'Begin with non-transactional policy context request through a warm trade channel.',
    outreach_angle = 'Energy transition expansion with local partnership and policy alignment.',
    value_proposition = 'Capital and operating expertise aligned to regional transition priorities.',
    proof_points = array['Sponsor track record','Transition impact thesis','Local partnership intent'],
    materials_required = array['Market-entry memo','Government-contact protocol','Sponsor credentials'],
    diligence_requirements = array['Role history','Regulatory map','Local partner screening','Election-cycle risk'],
    data_room_status = 'No data room; research files only',
    confidentiality_level = 'confidential',
    conflict_constraints = 'Avoid active concession or tariff-setting discussions.',
    competitive_landscape = 'Domestic energy incumbents and politically favored developers.',
    incumbent_relationships = 'Map local utility and ministry relationships before sponsor outreach.',
    risks = 'Policy volatility, public-sector optics, tariff politics, intermediary quality.',
    blockers = 'Unverified current authority of Rafael Santos and unclear ministry protocol.',
    open_questions = array['Is Rafael currently empowered to advise?','Which energy subsectors are politically viable?','Which local partners are conflict-free?'],
    success_criteria = array['Policy map delivered','Three compliant access paths','Two sponsor-qualified local counterparties'],
    disqualification_criteria = array['Requires lobbying registration beyond mandate','Introducer requests improper compensation'],
    next_milestone = 'Resolve Rafael Santos role history',
    owner = 'Latin America desk',
    priority = 'high',
    source_confidence = 0.74,
    last_reviewed_date = '2026-06-18',
    tags = array['energy-transition','market-entry','policy-access','latin-america'],
    notes = 'This is a protocol-sensitive access mandate more than a capital raise.'
  where id = '40000000-0000-4000-8000-000000000002';

  update mandates set
    mandate_category = 'Growth equity and strategic partnerships',
    deal_type = 'Investor search / strategic partnership',
    ask_type = 'Growth equity access, sovereign partner mapping, and strategic validation',
    transaction_type = 'Minority growth capital',
    client_profile = 'APAC logistics operator with regional expansion ambitions.',
    sponsor_profile = 'Founder-led operator seeking capital, strategic partners, and regional credibility.',
    jurisdiction = array['Singapore','Indonesia'],
    target_counterparty_types = array['Growth equity funds','sovereign-linked investors','strategic logistics groups','family offices'],
    desired_counterparties = array['Harborline Growth','regional logistics platforms','Singapore-based family offices'],
    forbidden_contacts = array['Direct competitors under NDA or portfolio conflict'],
    capital_type = 'Minority growth equity',
    capital_stack = 'Primary equity with possible strategic co-investment',
    target_amount = 'USD 40M-75M',
    minimum_ticket = 'USD 10M',
    currency = 'USD / SGD',
    economics = 'Expansion capital for regional route density and technology upgrades.',
    fee_model = 'Retainer plus capital introduction success fee',
    transaction_stage = 'Draft mandate',
    timeline = 'Four to six months after materials are ready',
    urgency = 'medium',
    decision_deadline = '2026-10-01',
    close_target_date = '2027-01-31',
    regulatory_regime = 'Foreign investment, logistics licensing, data and customs compliance',
    compliance_requirements = 'Investor KYC, sanctions screening, competitor NDA review',
    sanctions_exposure = 'Low; screen shipping counterparties and beneficial owners.',
    political_exposure = 'Moderate due to sovereign-linked capital and cross-border logistics.',
    procurement_process = 'Private transaction; partnership agreements may trigger regulatory filings.',
    government_touchpoints = array['Investment promotion agencies','customs and logistics regulators'],
    required_approvals = array['Founder approval','Board approval','NDA conflict review'],
    decision_makers = array['Founder','CFO','lead investor partner'],
    gatekeepers = array['Corporate development lead','fund operating partner','family office advisor'],
    influencers = array['Maya Chen','regional logistics executives','sovereign investment advisors'],
    buyer_universe = array['Strategic logistics operators','e-commerce infrastructure groups'],
    investor_universe = array['Growth equity','family offices','sovereign-linked funds'],
    strategic_partners = array['Regional logistics platforms','port-adjacent operators','technology vendors'],
    relationship_thesis = 'Maya Chen can validate growth narrative and surface investor/sovereign logistics paths.',
    access_strategy = 'Use logistics-sector thesis and conference context before investor ask.',
    outreach_angle = 'Regional logistics platform with route density and sovereign-aligned infrastructure relevance.',
    value_proposition = 'Growth-ready operator with cross-border logistics footprint.',
    proof_points = array['Revenue growth','route density','customer concentration','technology roadmap'],
    materials_required = array['Teaser','financial model','customer cohort analysis','NDA-approved investor deck'],
    diligence_requirements = array['Financial quality of earnings','customer concentration','license review','competitor conflict map'],
    data_room_status = 'Not ready',
    confidentiality_level = 'confidential',
    conflict_constraints = 'Avoid investors with direct competitor portfolio conflict.',
    competitive_landscape = 'Regional consolidators, platform logistics groups, sovereign-backed operators.',
    incumbent_relationships = 'Existing founder investor relationships should be mapped before outreach.',
    risks = 'Data room not ready, valuation expectations, competitor conflicts.',
    blockers = 'Forbidden contact list and target investor profile are incomplete.',
    open_questions = array['Which investors are off-limits?','What valuation range is acceptable?','Is sovereign-linked capital welcome?'],
    success_criteria = array['Investor shortlist','Five qualified warm paths','Two strategic partner conversations'],
    disqualification_criteria = array['Direct competitor exposure','No logistics thesis','Ticket size below threshold'],
    next_milestone = 'Define forbidden contacts before matching',
    owner = 'APAC growth desk',
    priority = 'medium',
    source_confidence = 0.7,
    last_reviewed_date = '2026-06-15',
    tags = array['growth-equity','logistics','apac','strategic-partnership'],
    notes = 'Investor readiness depends on cleaner materials and tighter exclusion rules.'
  where id = '40000000-0000-4000-8000-000000000003';

  insert into outreach_queue (
    id, workspace_id, person_id, mandate_id, person_name, mandate_title, reason, channel, relationship_strength,
    risk_level, due_date, status
  ) values
  (
    '50000000-0000-4000-8000-000000000001',
    seeded_workspace_id,
    '00000000-0000-4000-8000-000000000001',
    '40000000-0000-4000-8000-000000000001',
    'Amelia Hart',
    'Port Modernization Capital Path',
    'Direct relationship with infrastructure mandate fit and fund authority.',
    'email',
    5,
    'low',
    '2026-06-25',
    'draft_ready'
  ),
  (
    '50000000-0000-4000-8000-000000000002',
    seeded_workspace_id,
    '00000000-0000-4000-8000-000000000002',
    '40000000-0000-4000-8000-000000000002',
    'Rafael Santos',
    'Latin America Energy Introductions',
    'Government trade role maps to energy market access, but current authority needs review.',
    'intro_request',
    4,
    'medium',
    '2026-06-28',
    'awaiting_approval'
  ),
  (
    '50000000-0000-4000-8000-000000000003',
    seeded_workspace_id,
    '00000000-0000-4000-8000-000000000004',
    '40000000-0000-4000-8000-000000000001',
    'James Okafor',
    'Port Modernization Capital Path',
    'Possible development-finance path, but duplicate identity must be resolved first.',
    'email',
    2,
    'unknown',
    '2026-07-01',
    'draft_needed'
  )
  on conflict (id) do update set
    workspace_id = excluded.workspace_id,
    person_id = excluded.person_id,
    mandate_id = excluded.mandate_id,
    person_name = excluded.person_name,
    mandate_title = excluded.mandate_title,
    reason = excluded.reason,
    channel = excluded.channel,
    relationship_strength = excluded.relationship_strength,
    risk_level = excluded.risk_level,
    due_date = excluded.due_date,
    status = excluded.status,
    deleted_at = null,
    updated_at = now();

  insert into review_tasks (id, workspace_id, title, detail, status) values
  (
    '60000000-0000-4000-8000-000000000001',
    seeded_workspace_id,
    'Rafael Santos role change',
    'Public profile suggests new ministry title; preserve prior private-sector card role.',
    'needs_review'
  ),
  (
    '60000000-0000-4000-8000-000000000002',
    seeded_workspace_id,
    'James Okafor duplicate',
    'Two card scans share phone number but differ by organization and date.',
    'suggested'
  ),
  (
    '60000000-0000-4000-8000-000000000003',
    seeded_workspace_id,
    'Maya Chen stale contact',
    'Known contact with active APAC mandate relevance and no interaction in 7 months.',
    'stale'
  )
  on conflict (id) do update set
    workspace_id = excluded.workspace_id,
    title = excluded.title,
    detail = excluded.detail,
    status = excluded.status,
    deleted_at = null,
    updated_at = now();
end $$;
