import type { Interaction, Mandate, Organization, OutreachItem, Person, ReviewTask, Role } from "@/types/domain";

export const people: Person[] = [
  {
    id: "p-amelia-hart",
    canonicalName: "Amelia Hart",
    displayName: "Amelia Hart",
    aliases: ["A. Hart"],
    relationshipStrength: 5,
    trustLevel: "high",
    warmthStatus: "direct",
    currentTitle: "Partner, Strategic Infrastructure",
    currentOrganization: "Northbridge Capital",
    lastInteraction: "2026-05-18",
    geography: "London / New York",
    sectorTags: ["Infrastructure", "Energy", "Sovereign"],
    sourceCount: 9,
    mandateMatches: 3,
    reviewStatus: "verified",
    notes: "Can be approached directly when the ask is precise and well-framed.",
    opposition: "May face resistance from incumbent port operators and local ministries wary of foreign capital control.",
    nationality: "United Kingdom",
    languages: ["English", "French"],
    publicPrivateStatus: "Public-private bridge",
    influenceType: "Introducer / capital allocator",
    accessPath: "Direct relationship; best through a precise one-page mandate brief.",
    relationshipOwner: "Private operator desk",
    bestApproach: "Formal email followed by a short working call.",
    currentAuthority: "Can validate fund appetite and introduce infrastructure counterparties.",
    historicalAuthority: "Former UK trade role gives context on sovereign and ministry channels.",
    sensitivityLevel: "moderate",
    motivations: "High-quality infrastructure mandates, credible counterparties, reputationally clean capital.",
    constraints: "Avoid appearing to lobby former government colleagues informally.",
    relevantMandates: ["Port Modernization Capital Path"],
    relevantGeographies: ["United Kingdom", "West Africa"],
    relevantSectors: ["Infrastructure", "Energy"],
    relevantInstitutions: ["Northbridge Capital", "UK Department for Business and Trade"],
    keyRelationships: "Former trade officials, infrastructure fund partners, UK-Africa commercial channels.",
    doNotDiscuss: "Do not frame the ask as political access or privileged government influence.",
    bestNextMove: "Send targeted infrastructure brief after mandate terms are tightened.",
    sourceConfidence: 0.92,
    lastVerifiedDate: "2026-05-18"
  },
  {
    id: "p-rafael-santos",
    canonicalName: "Rafael Santos",
    displayName: "Rafael Santos",
    aliases: ["Rafa Santos"],
    relationshipStrength: 4,
    trustLevel: "moderate",
    warmthStatus: "warm",
    currentTitle: "Senior Advisor",
    currentOrganization: "Ministry of Trade, Brazil",
    lastInteraction: "2026-03-07",
    geography: "Brasilia",
    sectorTags: ["Government", "Trade", "Latin America"],
    sourceCount: 6,
    mandateMatches: 2,
    reviewStatus: "needs_review",
    notes: "Historical card indicates prior private-sector role that may matter for energy mandate.",
    opposition: "Likely constrained by domestic political scrutiny around energy privatization and trade concessions.",
    nationality: "Brazil",
    languages: ["Portuguese", "English", "Spanish"],
    publicPrivateStatus: "Government",
    influenceType: "Policy advisor / gatekeeper",
    accessPath: "Warm path; requires policy-safe framing and ministry protocol.",
    relationshipOwner: "Latin America coverage",
    bestApproach: "Intro request through trusted trade contact with noncommercial policy context.",
    currentAuthority: "Can interpret ministry priorities and direct appropriate energy-policy access points.",
    historicalAuthority: "Prior private-sector advisory work may explain sponsor relationships.",
    sensitivityLevel: "high",
    motivations: "Trade development, national energy security, avoiding public-sector controversy.",
    constraints: "Procurement optics and domestic political sensitivity around privatization.",
    relevantMandates: ["Latin America Energy Introductions"],
    relevantGeographies: ["Brazil", "Chile"],
    relevantSectors: ["Government", "Energy", "Trade"],
    relevantInstitutions: ["Ministry of Trade, Brazil"],
    keyRelationships: "Ministry staff, trade attachés, energy transition sponsors.",
    doNotDiscuss: "Avoid commercial compensation, preferential access, or concession language.",
    bestNextMove: "Resolve current title and confirm whether private-sector role remains relevant.",
    sourceConfidence: 0.78,
    lastVerifiedDate: "2026-03-07"
  },
  {
    id: "p-maya-chen",
    canonicalName: "Maya Chen",
    displayName: "Maya Chen",
    aliases: [],
    relationshipStrength: 3,
    trustLevel: "moderate",
    warmthStatus: "known",
    currentTitle: "Managing Director",
    currentOrganization: "Harborline Growth",
    lastInteraction: "2025-11-12",
    geography: "Singapore",
    sectorTags: ["Growth Equity", "Logistics", "APAC"],
    sourceCount: 4,
    mandateMatches: 1,
    reviewStatus: "verified",
    notes: "Best reached through an event-specific pretext or a mutual Asia logistics contact.",
    opposition: "Competitive tension with regional logistics consolidators and sovereign-linked investors.",
    nationality: "Singapore",
    languages: ["English", "Mandarin"],
    publicPrivateStatus: "Private sector",
    influenceType: "Investor / sector validator",
    accessPath: "Event-specific pretext or mutual APAC logistics contact.",
    relationshipOwner: "APAC growth desk",
    bestApproach: "Conference follow-up with a focused logistics growth thesis.",
    currentAuthority: "Can validate growth equity appetite and identify regional operating sponsors.",
    historicalAuthority: "Known logistics network across Singapore and Indonesia.",
    sensitivityLevel: "moderate",
    motivations: "Scalable logistics platforms, credible operators, regional growth visibility.",
    constraints: "Avoid conflicts with existing portfolio or sovereign-linked co-investors.",
    relevantMandates: ["Strategic Growth Equity Access"],
    relevantGeographies: ["Singapore", "Indonesia"],
    relevantSectors: ["Growth Equity", "Logistics"],
    relevantInstitutions: ["Harborline Growth"],
    keyRelationships: "APAC logistics operators, growth funds, conference network.",
    doNotDiscuss: "Avoid naming competitors without permission.",
    bestNextMove: "Use a logistics event as the opening context.",
    sourceConfidence: 0.84,
    lastVerifiedDate: "2025-11-12"
  },
  {
    id: "p-james-okafor",
    canonicalName: "James Okafor",
    displayName: "James Okafor",
    aliases: ["J. Okafor"],
    relationshipStrength: 2,
    trustLevel: "unknown",
    warmthStatus: "weak",
    currentTitle: "Board Member",
    currentOrganization: "Atlantic Development Bank",
    lastInteraction: "2024-09-22",
    geography: "Accra / Lagos",
    sectorTags: ["Development Finance", "Ports", "Africa"],
    sourceCount: 3,
    mandateMatches: 2,
    reviewStatus: "possible_duplicate",
    notes: "Two cards may be the same person with title progression.",
    opposition: "Possible board-level caution around reputational exposure and development-bank procurement rules.",
    nationality: "Ghana / Nigeria",
    languages: ["English"],
    publicPrivateStatus: "Development finance",
    influenceType: "Board validator / institutional gatekeeper",
    accessPath: "Indirect path; duplicate identity should be resolved before outreach.",
    relationshipOwner: "Africa infrastructure coverage",
    bestApproach: "Confirm identity, then approach through an institutional context.",
    currentAuthority: "May validate development-finance fit and identify governance concerns.",
    historicalAuthority: "Prior board and card history may show title progression.",
    sensitivityLevel: "high",
    motivations: "Governance quality, development impact, procurement integrity.",
    constraints: "Development-bank procurement rules and reputational exposure.",
    relevantMandates: ["Port Modernization Capital Path"],
    relevantGeographies: ["West Africa", "Ghana", "Nigeria"],
    relevantSectors: ["Development Finance", "Ports"],
    relevantInstitutions: ["Atlantic Development Bank"],
    keyRelationships: "Development bank board members, port finance contacts.",
    doNotDiscuss: "Do not imply bypassing procurement or board process.",
    bestNextMove: "Resolve duplicate records before any mandate-specific outreach.",
    sourceConfidence: 0.64,
    lastVerifiedDate: "2024-09-22"
  }
];

export const organizations: Organization[] = [
  {
    id: "o-northbridge",
    name: "Northbridge Capital",
    normalizedName: "northbridge capital",
    type: "fund",
    sector: "Infrastructure",
    country: "United Kingdom",
    city: "London",
    tags: ["fund", "infrastructure", "energy"]
  },
  {
    id: "o-trade-brazil",
    name: "Ministry of Trade, Brazil",
    normalizedName: "ministry of trade brazil",
    type: "government",
    sector: "Trade",
    country: "Brazil",
    city: "Brasilia",
    tags: ["government", "latin-america"]
  },
  {
    id: "o-harborline",
    name: "Harborline Growth",
    normalizedName: "harborline growth",
    type: "fund",
    sector: "Growth Equity",
    country: "Singapore",
    city: "Singapore",
    tags: ["apac", "logistics", "fund"]
  }
];

export const roles: Role[] = [
  {
    id: "r-1",
    personId: "p-amelia-hart",
    organizationName: "Northbridge Capital",
    title: "Partner, Strategic Infrastructure",
    startDate: "2023",
    isCurrent: true,
    confidence: 0.92,
    sourceLabel: "Manual update"
  },
  {
    id: "r-2",
    personId: "p-amelia-hart",
    organizationName: "UK Department for Business and Trade",
    title: "Deputy Trade Commissioner",
    startDate: "2012",
    endDate: "2018",
    isCurrent: false,
    confidence: 0.86,
    sourceLabel: "Business card OCR"
  },
  {
    id: "r-3",
    personId: "p-amelia-hart",
    organizationName: "Helios Energy Group",
    title: "Head of Public-Private Partnerships",
    startDate: "2018",
    endDate: "2023",
    isCurrent: false,
    confidence: 0.78,
    sourceLabel: "Public profile"
  }
];

export const interactions: Interaction[] = [
  {
    id: "i-1",
    personId: "p-amelia-hart",
    date: "2026-05-18",
    type: "call",
    summary: "Discussed sovereign-backed port modernization mandate and likely counterparties.",
    outcome: "Open to a specific one-page ask.",
    nextStep: "Send targeted brief after mandate terms are tightened.",
    confidence: 0.95,
    sourceLabel: "User note"
  },
  {
    id: "i-2",
    personId: "p-amelia-hart",
    date: "2025-10-04",
    type: "event",
    summary: "Reconnected at infrastructure forum; mentioned move from energy advisory into fund role.",
    confidence: 0.84,
    sourceLabel: "Event note"
  },
  {
    id: "i-3",
    personId: "p-amelia-hart",
    date: "2012",
    type: "note",
    summary: "Original card captured Deputy Trade Commissioner title and London office number.",
    confidence: 0.76,
    sourceLabel: "Business card OCR"
  }
];

export const mandates: Mandate[] = [
  {
    id: "m-port-modernization",
    clientName: "Confidential infrastructure client",
    title: "Port Modernization Capital Path",
    objective: "Identify warm government and fund counterparties for port modernization financing.",
    mandateCategory: "Infrastructure finance",
    dealType: "PPP / concession financing",
    askType: "Capital path, government access, and strategic counterparty mapping",
    transactionType: "Public-private infrastructure modernization",
    clientProfile: "Private infrastructure operator seeking credible sovereign-adjacent financing paths.",
    sponsorProfile: "Operator-led platform with port modernization mandate and public-sector interfaces.",
    sector: "Infrastructure",
    geography: ["West Africa", "United Kingdom"],
    jurisdiction: ["United Kingdom", "Ghana", "Nigeria"],
    targetCounterpartyTypes: ["Infrastructure funds", "DFIs", "trade ministries", "port authorities", "sovereign advisors"],
    desiredCounterparties: ["Northbridge Capital", "UK Department for Business and Trade", "Atlantic Development Bank"],
    forbiddenContacts: ["Direct procurement officials before counsel approval"],
    capitalType: "Project finance / structured growth capital",
    capitalStack: "Senior debt, DFI tranche, strategic equity, political risk insurance",
    targetAmount: "USD 150M-300M",
    minimumTicket: "USD 25M",
    currency: "USD",
    economics: "Long-dated infrastructure yield with concession-linked cash flow.",
    feeModel: "Success fee plus advisory retainer",
    transactionStage: "Mandate shaping",
    timeline: "Six to nine months to credible financing path",
    urgency: "high",
    decisionDeadline: "2026-08-15",
    closeTargetDate: "2027-03-31",
    regulatoryRegime: "Port concession, foreign investment, procurement, development-finance safeguards",
    complianceRequirements: "Anti-bribery, sanctions screening, beneficial ownership, public procurement review",
    sanctionsExposure: "Low direct exposure; screen contractors, port users, and state-linked counterparties.",
    politicalExposure: "High because port infrastructure touches sovereign logistics and labor interests.",
    procurementProcess: "Must avoid informal bypass of public tender or concession amendment process.",
    governmentTouchpoints: ["Trade ministry", "Port authority", "Investment promotion agency"],
    requiredApprovals: ["Client board", "Local counsel", "Procurement counsel", "Government relations review"],
    decisionMakers: ["Client CEO", "Ministerial sponsor", "Port authority board", "DFI investment committee"],
    gatekeepers: ["Chief of staff", "Legal counsel", "Development bank country lead"],
    influencers: ["Former trade officials", "Infrastructure fund partners", "Port operating advisors"],
    buyerUniverse: ["Strategic port operators", "Infrastructure platforms"],
    investorUniverse: ["Infrastructure funds", "DFIs", "Sovereign-linked capital", "Pension capital"],
    strategicPartners: ["Engineering firms", "Political risk insurers", "Local operators"],
    relationshipThesis: "Amelia Hart bridges fund authority and UK-Africa trade infrastructure context.",
    accessStrategy: "Start with validated fund appetite, then move to government-facing introductions only after compliance framing.",
    outreachAngle: "Modernization finance with transparent governance and development impact.",
    valueProposition: "Credible operator, bankable modernization plan, de-risked government interface.",
    proofPoints: ["Existing operator mandate", "Modernization capex plan", "Trade corridor impact"],
    materialsRequired: ["One-page mandate", "Capex summary", "Governance memo", "Counterparty shortlist"],
    diligenceRequirements: ["Concession status", "Environmental and social review", "Beneficial ownership", "Procurement history"],
    dataRoomStatus: "Early materials only",
    confidentialityLevel: "highly_confidential",
    conflictConstraints: "Avoid current procurement officials and any conflicted former advisors.",
    competitiveLandscape: "Incumbent port operators and regional logistics groups may resist new capital path.",
    incumbentRelationships: "Existing local operator relationships need mapping before outreach.",
    risks: "Political optics, procurement sensitivity, concession ambiguity, labor opposition.",
    blockers: "Unclear concession amendment path and uncertain ministry sponsor.",
    openQuestions: ["Who is the legitimate public-sector sponsor?", "What concession rights can be financed?", "Which DFI safeguards apply?"],
    successCriteria: ["Three warm investor conversations", "One government-safe access path", "Compliance-approved outreach narrative"],
    disqualificationCriteria: ["Requires improper public official contact", "Counterparty fails sanctions or beneficial ownership review"],
    nextMilestone: "Approve one-page mandate and compliance-safe outreach angle",
    owner: "Infrastructure desk",
    priority: "critical",
    sourceConfidence: 0.86,
    lastReviewedDate: "2026-06-20",
    tags: ["PPP", "ports", "project-finance", "sovereign-interface"],
    notes: "Treat as relationship-led origination with strict compliance gating.",
    status: "active",
    relevantContacts: 11,
    nextAction: "Approve outreach angle for Amelia Hart"
  },
  {
    id: "m-energy-transition",
    clientName: "Energy transition sponsor",
    title: "Latin America Energy Introductions",
    objective: "Map trade and energy-policy access points for regional expansion.",
    mandateCategory: "Market entry and policy access",
    dealType: "Government access / strategic expansion",
    askType: "Policy readout, regulator mapping, and energy-sector introductions",
    transactionType: "Cross-border market entry",
    clientProfile: "Energy transition sponsor evaluating Latin America expansion.",
    sponsorProfile: "Commercial sponsor seeking policy-safe introductions before capital deployment.",
    sector: "Energy",
    geography: ["Brazil", "Chile"],
    jurisdiction: ["Brazil", "Chile"],
    targetCounterpartyTypes: ["Trade advisors", "energy regulators", "ministry policy staff", "local sponsors", "utilities"],
    desiredCounterparties: ["Ministry of Trade, Brazil", "energy transition sponsors", "regional utilities"],
    forbiddenContacts: ["Officials involved in active procurement processes"],
    capitalType: "Strategic expansion capital",
    capitalStack: "Sponsor equity with potential local debt",
    targetAmount: "To be defined after market access readout",
    minimumTicket: "N/A",
    currency: "USD / BRL / CLP",
    economics: "Market-entry optionality before project-level commitment.",
    feeModel: "Monthly advisory plus milestone fee",
    transactionStage: "Researching",
    timeline: "Ninety-day access and policy map",
    urgency: "medium",
    decisionDeadline: "2026-09-01",
    closeTargetDate: "2026-12-15",
    regulatoryRegime: "Energy policy, foreign investment, trade promotion, utility regulation",
    complianceRequirements: "Government contact protocol, anti-bribery review, lobbying analysis",
    sanctionsExposure: "Low but screen local intermediaries and politically exposed persons.",
    politicalExposure: "Medium-high due to energy pricing, privatization sensitivity, and elections.",
    procurementProcess: "No procurement participation until counsel defines guardrails.",
    governmentTouchpoints: ["Trade ministry", "Energy regulator", "Investment promotion agencies"],
    requiredApprovals: ["Client strategy lead", "Government-contact protocol", "Local counsel"],
    decisionMakers: ["Sponsor CEO", "Regional expansion lead", "Policy sponsor"],
    gatekeepers: ["Ministry advisor", "Trade attaché", "Local legal counsel"],
    influencers: ["Former energy officials", "utility executives", "trade associations"],
    buyerUniverse: ["Utilities", "industrial offtakers", "regional developers"],
    investorUniverse: ["Strategic energy investors", "climate funds", "local banks"],
    strategicPartners: ["Local developers", "utility partners", "policy advisors"],
    relationshipThesis: "Rafael Santos may clarify policy context but needs role-history resolution before approach.",
    accessStrategy: "Begin with non-transactional policy context request through a warm trade channel.",
    outreachAngle: "Energy transition expansion with local partnership and policy alignment.",
    valueProposition: "Capital and operating expertise aligned to regional transition priorities.",
    proofPoints: ["Sponsor track record", "Transition impact thesis", "Local partnership intent"],
    materialsRequired: ["Market-entry memo", "Government-contact protocol", "Sponsor credentials"],
    diligenceRequirements: ["Role history", "Regulatory map", "Local partner screening", "Election-cycle risk"],
    dataRoomStatus: "No data room; research files only",
    confidentialityLevel: "confidential",
    conflictConstraints: "Avoid active concession or tariff-setting discussions.",
    competitiveLandscape: "Domestic energy incumbents and politically favored developers.",
    incumbentRelationships: "Map local utility and ministry relationships before sponsor outreach.",
    risks: "Policy volatility, public-sector optics, tariff politics, intermediary quality.",
    blockers: "Unverified current authority of Rafael Santos and unclear ministry protocol.",
    openQuestions: ["Is Rafael currently empowered to advise?", "Which energy subsectors are politically viable?", "Which local partners are conflict-free?"],
    successCriteria: ["Policy map delivered", "Three compliant access paths", "Two sponsor-qualified local counterparties"],
    disqualificationCriteria: ["Requires lobbying registration beyond mandate", "Introducer requests improper compensation"],
    nextMilestone: "Resolve Rafael Santos role history",
    owner: "Latin America desk",
    priority: "high",
    sourceConfidence: 0.74,
    lastReviewedDate: "2026-06-18",
    tags: ["energy-transition", "market-entry", "policy-access", "latin-america"],
    notes: "This is a protocol-sensitive access mandate more than a capital raise.",
    status: "researching",
    relevantContacts: 7,
    nextAction: "Resolve Rafael Santos role history"
  },
  {
    id: "m-apac-logistics",
    clientName: "APAC logistics operator",
    title: "Strategic Growth Equity Access",
    objective: "Find investor and sovereign logistics paths across Singapore and Indonesia.",
    mandateCategory: "Growth equity and strategic partnerships",
    dealType: "Investor search / strategic partnership",
    askType: "Growth equity access, sovereign partner mapping, and strategic validation",
    transactionType: "Minority growth capital",
    clientProfile: "APAC logistics operator with regional expansion ambitions.",
    sponsorProfile: "Founder-led operator seeking capital, strategic partners, and regional credibility.",
    sector: "Logistics",
    geography: ["Singapore", "Indonesia"],
    jurisdiction: ["Singapore", "Indonesia"],
    targetCounterpartyTypes: ["Growth equity funds", "sovereign-linked investors", "strategic logistics groups", "family offices"],
    desiredCounterparties: ["Harborline Growth", "regional logistics platforms", "Singapore-based family offices"],
    forbiddenContacts: ["Direct competitors under NDA or portfolio conflict"],
    capitalType: "Minority growth equity",
    capitalStack: "Primary equity with possible strategic co-investment",
    targetAmount: "USD 40M-75M",
    minimumTicket: "USD 10M",
    currency: "USD / SGD",
    economics: "Expansion capital for regional route density and technology upgrades.",
    feeModel: "Retainer plus capital introduction success fee",
    transactionStage: "Draft mandate",
    timeline: "Four to six months after materials are ready",
    urgency: "medium",
    decisionDeadline: "2026-10-01",
    closeTargetDate: "2027-01-31",
    regulatoryRegime: "Foreign investment, logistics licensing, data and customs compliance",
    complianceRequirements: "Investor KYC, sanctions screening, competitor NDA review",
    sanctionsExposure: "Low; screen shipping counterparties and beneficial owners.",
    politicalExposure: "Moderate due to sovereign-linked capital and cross-border logistics.",
    procurementProcess: "Private transaction; partnership agreements may trigger regulatory filings.",
    governmentTouchpoints: ["Investment promotion agencies", "customs and logistics regulators"],
    requiredApprovals: ["Founder approval", "Board approval", "NDA conflict review"],
    decisionMakers: ["Founder", "CFO", "lead investor partner"],
    gatekeepers: ["Corporate development lead", "fund operating partner", "family office advisor"],
    influencers: ["Maya Chen", "regional logistics executives", "sovereign investment advisors"],
    buyerUniverse: ["Strategic logistics operators", "e-commerce infrastructure groups"],
    investorUniverse: ["Growth equity", "family offices", "sovereign-linked funds"],
    strategicPartners: ["Regional logistics platforms", "port-adjacent operators", "technology vendors"],
    relationshipThesis: "Maya Chen can validate growth narrative and surface investor/sovereign logistics paths.",
    accessStrategy: "Use logistics-sector thesis and conference context before investor ask.",
    outreachAngle: "Regional logistics platform with route density and sovereign-aligned infrastructure relevance.",
    valueProposition: "Growth-ready operator with cross-border logistics footprint.",
    proofPoints: ["Revenue growth", "route density", "customer concentration", "technology roadmap"],
    materialsRequired: ["Teaser", "financial model", "customer cohort analysis", "NDA-approved investor deck"],
    diligenceRequirements: ["Financial quality of earnings", "customer concentration", "license review", "competitor conflict map"],
    dataRoomStatus: "Not ready",
    confidentialityLevel: "confidential",
    conflictConstraints: "Avoid investors with direct competitor portfolio conflict.",
    competitiveLandscape: "Regional consolidators, platform logistics groups, sovereign-backed operators.",
    incumbentRelationships: "Existing founder investor relationships should be mapped before outreach.",
    risks: "Data room not ready, valuation expectations, competitor conflicts.",
    blockers: "Forbidden contact list and target investor profile are incomplete.",
    openQuestions: ["Which investors are off-limits?", "What valuation range is acceptable?", "Is sovereign-linked capital welcome?"],
    successCriteria: ["Investor shortlist", "Five qualified warm paths", "Two strategic partner conversations"],
    disqualificationCriteria: ["Direct competitor exposure", "No logistics thesis", "Ticket size below threshold"],
    nextMilestone: "Define forbidden contacts before matching",
    owner: "APAC growth desk",
    priority: "medium",
    sourceConfidence: 0.7,
    lastReviewedDate: "2026-06-15",
    tags: ["growth-equity", "logistics", "apac", "strategic-partnership"],
    notes: "Investor readiness depends on cleaner materials and tighter exclusion rules.",
    status: "draft",
    relevantContacts: 5,
    nextAction: "Define forbidden contacts before matching"
  }
];

export const outreachQueue: OutreachItem[] = [
  {
    id: "q-1",
    personName: "Amelia Hart",
    mandateTitle: "Port Modernization Capital Path",
    reason: "Direct relationship with infrastructure mandate fit and fund authority.",
    channel: "email",
    relationshipStrength: 5,
    riskLevel: "low",
    dueDate: "2026-06-25",
    status: "draft_ready"
  },
  {
    id: "q-2",
    personName: "Rafael Santos",
    mandateTitle: "Latin America Energy Introductions",
    reason: "Government trade role maps to energy market access, but current authority needs review.",
    channel: "intro_request",
    relationshipStrength: 4,
    riskLevel: "medium",
    dueDate: "2026-06-28",
    status: "awaiting_approval"
  },
  {
    id: "q-3",
    personName: "James Okafor",
    mandateTitle: "Port Modernization Capital Path",
    reason: "Possible development-finance path, but duplicate identity must be resolved first.",
    channel: "email",
    relationshipStrength: 2,
    riskLevel: "unknown",
    dueDate: "2026-07-01",
    status: "draft_needed"
  }
];

export const reviewTasks: ReviewTask[] = [
  {
    id: "t-1",
    title: "Rafael Santos role change",
    detail: "Public profile suggests new ministry title; preserve prior private-sector card role.",
    status: "needs_review"
  },
  {
    id: "t-2",
    title: "James Okafor duplicate",
    detail: "Two card scans share phone number but differ by organization and date.",
    status: "suggested"
  },
  {
    id: "t-3",
    title: "Maya Chen stale contact",
    detail: "Known contact with active APAC mandate relevance and no interaction in 7 months.",
    status: "stale"
  }
];
